# Generated by Django 3.2.4 on 2021-06-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='nama_opd',
            field=models.CharField(max_length=255),
        ),
    ]
