# Generated by Django 3.2.4 on 2021-06-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnk', '0002_alter_opd_nama_opd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='aktif',
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('hidup', 'hidup'), ('mati', 'mati')], max_length=200, null=True),
        ),
    ]
