# Generated by Django 3.2.4 on 2021-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnk', '0004_alter_asset_masa_aktif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('hidup', 'hidup'), ('mati', 'mati'), ('peringatan', 'peringatan')], max_length=200, null=True),
        ),
    ]
