# Generated by Django 3.2.4 on 2021-06-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnk', '0005_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='masa_aktif',
            field=models.DateField(),
        ),
    ]
