# Generated by Django 3.2.4 on 2021-06-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stnk', '0006_alter_asset_masa_aktif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='masa_aktif',
            field=models.DateTimeField(),
        ),
    ]
